
name: Build code and deploy to server

on:
  push:
    branches: 
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
jobs:
  build:
    name: Build Code
    runs-on: ubuntu-20.04
    steps:
    - name: Setup Node
      uses: actions/setup-node@v2.1.2
      with:
        node-version: '10.x'
    - name: Install Dependencies
      run: 
        npm install
        npm run build
    - name: "On branch dev: Deploy to Server"
      if: github.ref == 'refs/heads/dev'
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-avzr --delete"
          SOURCE: "build/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrects.REMOTE_PORT }}
          TARGET: '/home/nua/nginx/www/dev.ritachan.site'
    - name: "On branch master: Deploy to Server"
      if: github.ref == 'refs/heads/dev'
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-avzr --delete"
          SOURCE: "build/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrects.REMOTE_PORT }}
          TARGET: '/home/nua/nginx/www/ritachan.site'
